theme: jekyll-theme-cayman
github:
  macos_url: https://github.com/filipesperandio/WifiNoInternetz/releases/download/1.0.1/WifiNoInternetz.app.pkg
  windows_url: https://github.com/filipesperandio/WifiNoInternetz/releases/download/1.0.2/Setup.exe
